---
title: "Replication of Inferring Identity From Language: Linguistic Intergroup Bias Informs Social Categorization by Shanette C. Porter, Michelle Rheinschmidt-Same, and Jennifer A. Richeson (2016, Psychological Science)"
author: "Lindsey Hasak (lrhasak@stanford.edu)"
date: October 7, 2018
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---
[Github Repository](https://github.com/lrhasak/porter2016)
```{r}
setwd("/Users/lindseyhasak/Desktop/porter2016")
```

##Introduction

###Justification

Language can convey explicit information about a speaker's target topic, but also implicit information about the speaker themselves. In their 2016 study, Porter, Rheinschmidt-Same, and Richeson investigated the effect of linguistic intergroup bias (LIB) in conveying an otherwise-anonymous communicator's social identity. In study 1A, Porter et al. hypothesized that subtle linguistic cues in a statement could allow individuals to make assumptions about the communicator's political identity.

My broad research interests include language, reading, and literacy, specifically in regards to education. While I have previously focused on the cognitive aspects of these fields, I am interested in eventually exploring societal factors that impact children's literacy. For instance, how could a narrator's use of LIB affect reading comprehension for children with different social identities and backgrounds? I do not have any programming experience, which is why I decided to undertake a survey-based replication for this project. A future direction could be to examine children's recognition a passage given varying instances of LIB in a text.

###Stimuli and Procedures

To replicate this study, I will survey 88 participants over Amazon Mechanical Turk. Participants will be assigned to one of two conditions: "favorable" LIB and "unfavorable" LIB. Participants in both conditions will read a passage that begins: 
"Imagine that someone is communicating with you about a man named Peter. Peter is an American, has an interest in politics, and voted for Barack Obama."

Depending on the LIB group, particpants will then one of two communicator statement about Peter, which portray him more and less favorably. Porter et al. have listed these statements online. After reading both statements, participants will be asked to assess the communicator's political leanings (on a scale from 1-7; 1 being "definitely a Republican" and 7 being "definitely a Democrat") and then how likely Peter is to be helpful or rude in future situations. After completing these tasks, participants will complete a demographic questionnaire.

###Challenges

One difficulty will be working out financial compensation for participants within the context of the class budget. 
Another anticipated challenge is the feasibility of having data collection completed with enough time to comfortably organize and analyze the data, as I have never used R for a task of this magnitude before. I am hopeful that recruiting participants through MTurk will allow for faster data collection than if the survey were being administered in person.

##Citation
Porter, S. C., Rheinschmidt-Same, M., & Richeson, J. A. (2016). Inferring Identity From Language: Linguistic Intergroup Bias Informs Social Categorization. Psychological Science, 27(1), 94–102. https://doi.org/10.1177/0956797615612202

